site_name: DODAS go client
theme:
  name: material
  logo:
    icon: cloud_circle
  palette:
    primary: "Deep Blue"
    accent: "Light Blue"
nav:
  - Home: "README.md"
  - Quick start:
      - Standalone IM: "quick-start/standalone.md"
      - Community IM: "quick-start/community.md"
  - Reference Guide: "dodas.md"
repo_name: "dodas-ts/dodas-go-client"
repo_url: "https://github.com/DODAS-TS/dodas-go-client"
