cloud:
    id: os
    type: OpenStack
    host: my_cloud_endpoint
    # e.g. host: http://openstack.fisica.unipg.it:5000/
    username: my_username
    password: < PUT HERE YOUR OpenStack Password >
    tenant: my_os_tenant
    auth_version: 3.x_password
    domain: default
im:
    id: im
    type: InfrastructureManager
    host: https://im-dodas.cloud.cnaf.infn.it/infrastructures
    token: < PUT HERE YOUR IAM TOKEN >
## Uncomment this if you have an IAM exchange token client
#allowrefresh:
#    client_id: < YOUR EXCHANGE TOKEN CLIENT ID >
#    client_secret: < YOUR EXCHANGE TOKEN CLIENT SECRET >
#    iam_endpoint: https://dodas-iam.cloud.cnaf.infn.it/token
#    refresh_file: /tmp/.refresh_token
#    access_file: /tmp/.access_token
